#!/bin/sh
#
# Copyright (c) 2022-2026, Muktadiur Rahman <muktadiur@gmail.com>
# All rights reserved.

# PROVIDE: blockord
# REQUIRE: pf LOGIN
# KEYWORD: shutdown

# rcvar and *_cmd are consumed by the rc.subr framework, not this script.
# shellcheck disable=SC2034
# shellcheck source=/dev/null
. /etc/rc.subr

name="blockord"
rcvar="blockord_enable"

load_rc_config "$name"

: "${blockord_enable:=NO}"

start_cmd="/usr/local/bin/blockor start"
stop_cmd="/usr/local/bin/blockor stop"
restart_cmd="/usr/local/bin/blockor restart"
status_cmd="/usr/local/bin/blockor status"

run_rc_command "$1"
